import Header from "./components/header";
import IsNounceExist from "./components/isNounceExist";
import { StepProvider } from './components/cartStepsContext';
import { CartItemProvider } from './components/cartContext';
import  ReduxProvider  from './ReduxProvider';
import localFont from "next/font/local";
import "./globals.css";
import LoadCart from "./components/lib/loadCart";
import ProductDetailsModal from "./components/ui/productDetailsModal";
// import { NonceProvider } from "./components/nonceProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NonceProvider> */}
          {/* <StepProvider>
            <CartItemProvider> */}
              {/* <Header/> */}
              {/* <IsNounceExist /> */}
              {/* <div className="mt-10">
                  {children}
              </div> */}
            {/* </CartItemProvider>
          </StepProvider> */}

          <ReduxProvider>
            <Header/>
            <LoadCart/>
            {children}
            <ProductDetailsModal />
          </ReduxProvider>
        {/* </NonceProvider> */}
      </body>
    </html>
  );
}
